name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
       matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.0
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: chmod +x gradlew

    - name: Run Tests with Gradle
      run: ./gradlew test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-result-${{ matrix.os }}
        path: build/reports/tests
